from pathlib import Path
p = Path(r"C:\Users\ryanc\Desktop\SavingsTracker APP\profile.html")
text = p.read_text(encoding="utf-8")
text = text.replace("        <div class=\"user-info\">\n                <span class=\"user-name\" id=\"userName\"></span>\n                <button class=\"logout-btn\" onclick=\"logout()\">Sign Out</button>\n            </div>\n", "")
text = text.replace("        .member-since { color: #1e1b4b; }\n", "        .member-since { color: #1e1b4b; }\n\n        .profile-footer {\n            margin-top: 24px;\n            padding: 20px 24px;\n            border-radius: 20px;\n            background: white;\n            box-shadow: 0 10px 30px rgba(139, 92, 246, 0.04);\n            border: 1px solid rgba(139, 92, 246, 0.06);\n            display: flex;\n            align-items: center;\n            justify-content: space-between;\n            gap: 16px;\n            flex-wrap: wrap;\n        }\n\n        .profile-footer-copy {\n            display: flex;\n            flex-direction: column;\n            gap: 4px;\n            min-width: 0;\n        }\n\n        .profile-footer-label {\n            font-size: 12px;\n            font-weight: 700;\n            color: #9ca3af;\n            text-transform: uppercase;\n            letter-spacing: 0.5px;\n        }\n\n        .profile-footer-user {\n            font-size: 16px;\n            font-weight: 800;\n            color: #1e1b4b;\n            word-break: break-word;\n        }\n")
text = text.replace("            .actions button, .actions a {\n                width: 100%;\n                text-align: center;\n            }\n        }\n", "            .actions button, .actions a {\n                width: 100%;\n                text-align: center;\n            }\n\n            .profile-footer {\n                padding: 18px 16px;\n                flex-direction: column;\n                align-items: stretch;\n            }\n\n            .profile-footer .btn {\n                width: 100%;\n            }\n        }\n")
text = text.replace("        <div class=\"info-card\">\n            <h3>Security</h3>\n            <div class=\"form-group\">\n                <label>New Password</label>\n                <input type=\"password\" id=\"newPassword\" placeholder=\"Enter new password (min 6 chars)\">\n            </div>\n            <div class=\"form-group\">\n                <label>Confirm New Password</label>\n                <input type=\"password\" id=\"confirmPassword\" placeholder=\"Repeat new password\">\n            </div>\n            <div id=\"pwFeedback\" class=\"feedback\"></div>\n            <div class=\"actions\" style=\"margin-top: 16px;\">\n                <button class=\"btn btn-primary\" onclick=\"changePassword()\">Update Password</button>\n            </div>\n        </div>\n    </main>", "        <div class=\"info-card\">\n            <h3>Security</h3>\n            <div class=\"form-group\">\n                <label>New Password</label>\n                <input type=\"password\" id=\"newPassword\" placeholder=\"Enter new password (min 6 chars)\">\n            </div>\n            <div class=\"form-group\">\n                <label>Confirm New Password</label>\n                <input type=\"password\" id=\"confirmPassword\" placeholder=\"Repeat new password\">\n            </div>\n            <div id=\"pwFeedback\" class=\"feedback\"></div>\n            <div class=\"actions\" style=\"margin-top: 16px;\">\n                <button class=\"btn btn-primary\" onclick=\"changePassword()\">Update Password</button>\n            </div>\n        </div>\n\n        <div class=\"profile-footer\">\n            <div class=\"profile-footer-copy\">\n                <div class=\"profile-footer-label\">Signed in as</div>\n                <div class=\"profile-footer-user\" id=\"profileFooterUser\"></div>\n            </div>\n            <button class=\"btn btn-danger\" onclick=\"logout()\">Sign Out</button>\n        </div>\n    </main>")
text = text.replace("            document.getElementById('userName').textContent = '@' + username\n", "            document.getElementById('profileFooterUser').textContent = '@' + username\n")
p.write_text(text, encoding="utf-8", newline="")
